// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyInvitationApp.Data;

#nullable disable

namespace PartyInvitationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250306050706_SeedInvitationsData")]
    partial class SeedInvitationsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PartyInvitationApp.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuestEmail = "pmadziak@conestogac.on.ca",
                            GuestName = "Bob Jones",
                            PartyId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            GuestEmail = "peter.madziak@gmail.com",
                            GuestName = "Sally Smith",
                            PartyId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            GuestEmail = "bart.simpson@gmail.com",
                            GuestName = "Bart Simpson",
                            PartyId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            GuestEmail = "lisa.simpson@gmail.com",
                            GuestName = "Lisa Simpson",
                            PartyId = 3,
                            Status = 1
                        });
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New Year's Eve Blast!!",
                            Location = "Time Square, NY"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 30, 16, 43, 12, 0, DateTimeKind.Unspecified),
                            Description = "Drinks at Moe's Bar",
                            Location = "Moe's bar, Springfield"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 10, 20, 16, 43, 12, 0, DateTimeKind.Unspecified),
                            Description = "Thanksgiving Gathering",
                            Location = "Springfield"
                        });
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Invitation", b =>
                {
                    b.HasOne("PartyInvitationApp.Models.Party", "Party")
                        .WithMany("Invitations")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Party", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
